### ISSUE TITLE
[bug] [x86_64] Super Mario RPG hangs on Level UP

### ISSUE THREAD

**Issue by BlackLotus** [libretro/snes9x2005#13]
When leveling up (after the first fight) in Super Mario RPG the sound keeps going, but the graphics hang. Pressing keys doesn't help.
Tested with f4f4201f42bfb2acb98c654a3b384e79b1de588e and 64bit

**Comment by xperia64** [comment]
This also occurs on the Playstation Vita build, so at least it doesn't seem to be platform specific.

**Comment by xperia64** [comment]
I found the commit that caused this freeze. Unfortunately it's this one, which will take a while to go through: https://github.com/libretro/snes9x2005/commit/4a54fd4018adf931fb436acba2399efc6d6d1176

Note that to get in game at that commit, this must be applied first: https://github.com/libretro/snes9x2005/commit/735bc9b39a4eb1de6aef4c4b1af6e0b48d578bde
