### ISSUE TITLE
E.V.O - Search for Eden Glitches

### ISSUE THREAD

**Issue by Omnija** [libretro/snes9x2005#35]
While playing E.V.O i found some in game glitches which didn't occur with any of the other emulators.
While collecting meats gain of XP/Points sometimes displayed incorrectly. I also noticed that Hp does not stop at it's limit, so you can basically gain unlimited hp.
![05262017_220746](https://cloud.githubusercontent.com/assets/5616878/26514195/56888f8c-423e-11e7-9aab-29858a85e2f4.png)

**Comment by orbea** [comment]
@Omnija Can you still reproduce this issue?

**Comment by Omnija** [comment]
@orbea just tested and everything seems to work so far. Thanks

**Comment by orbea** [comment]
If it works now can you close this issue? Thanks!
