### ISSUE TITLE
3DS - Frameskip locks up system

### ISSUE THREAD

**Issue by MarioKartFan** [libretro/snes9x2005#83]
Tried checking out the latest development builds that include @jdgleaver latest pull requests.  Whenever I enable frame skipping (auto) under core options, it immediately locks up the system.

**Comment by jdgleaver** [comment]
I'm afraid that I cannot reproduce this - with the latest nightlies, auto frame skipping works correctly on all my 3DS consoles (it is even somewhat semi-usable on my o3DS).

What kind of lock up do you experience here? A full crash? A hang with the image still displayed on screen (with audio playback)? Do you get the same result with threaded video enabled/disabled?

**Comment by MarioKartFan** [comment]
Hello and thanks for the reply. I tried with a fresh config file and I can now set it properly. I assume there was something in the prior config file that contributed to the lockup.

**Comment by jdgleaver** [comment]
Thank you very much for confirming that it works :)

I guess we may never find out exactly which setting caused the bug, but if you encounter it again please do let me know!
